---
- name: Create MongoDB user in all clusters
  hosts: groups
  gather_facts: false
  tasks:
    - name: Check if node in cluster is a PRIMARY
      ansible.builtin.raw: |
        mongo -u <FIRST_DBA_USER> -p <FIRST_DBA_PASS> --authenticationDatabase admin --eval "rs.status().myState"
      register: is_primary

    - name: Create user if PRIMARY
      ansible.builtin.raw: |
        mongo -u <FIRST_DBA_USER> -p <FIRST_DBA_PASS> --authenticationDatabase admin --eval 'db.getSiblingDB("admin").createUser({user: "",pwd: "",roles: [{ role: "root", db: "admin" }]})'
      when: is_primary.stdout_lines[-1] | int == 1
      register: create_user

    - name: Output First Stage
      debug:
        var: is_primary.stdout_lines[-1]

    - name: Output Second Stage
      debug:
        var: create_user.stdout_lines